ALTER TABLE public.pilot_emergency_events
  ADD COLUMN IF NOT EXISTS seq bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS pilot_emergency_events_org_seq_idx
  ON public.pilot_emergency_events (organization_id, seq DESC);

REVOKE UPDATE, DELETE, TRUNCATE ON public.pilot_emergency_events FROM authenticated;